### PR TITLE
Release divviup-api 0.1.0

### PR DESCRIPTION
**Pull request by tgeoghegan**

### CODE REVIEW

**Comment by jbr** [comment]
Let's call this 0.1.0?

**Comment by jbr** [comment]
When this is rebased on main, there'll be several 0.0.30's that'll need to change to 0.1.0 — there's one in each of the tomls.

**Comment by jbr** [comment]
"rebased" in #612 since the lines moved around a bit

**Comment by tgeoghegan** [comment]
Yours has a better branch name. Closing.

**Pull request closed without merging**
